export const posts = [
  {
    _createdAt: "2025-01-26",
    views: 55,
    author: { _id: 4, name: "Jim West" },
    _id: 1,
    title: "CarSeller.io",
    description: "Second-hand car sales platform",
    image: "/img/mac.jpg",
    category: "tech",
  },
  {
    _createdAt: "2024-12-15",
    views: 120,
    author: { _id: 1, name: "Emily North" },
    _id: 2,
    title: "FoodieFinder",
    description: "Hyperlocal food delivery service",
    image: "/img/code.jpg",
    category: "tech",
  },
  {
    _createdAt: "2025-01-10",
    views: 30,
    author: { _id: 3, name: "Wendy South" },
    _id: 3,
    title: "EduConnect",
    description: "Online platform for personalized learning",
    image: "/img/writing.jpg",
    category: "education",
  },
  {
    _createdAt: "2024-11-28",
    views: 85,
    author: { _id: 2, name: "Lisa East" },
    _id: 4,
    title: "PetPal",
    description: "Social network for pet owners",
    image: "/img/typing.jpg",
    category: "social",
  },
  {
    _createdAt: "2025-01-20",
    views: 72,
    author: { _id: 5, name: "Carol Frond" },
    _id: 5,
    title: "EcoGrocer",
    description: "Sustainable online grocery store",
    image: "/img/eco.jpg",
    category: "eco",
  },
  {
    _createdAt: "2024-12-22",
    views: 105,
    author: { _id: 1, name: "Earl Grey" },
    _id: 6,
    title: "SkillShare+",
    description: "Upskilling platform connecting mentors and learners",
    image: "/img/work.jpg",
    category: "education",
  },
  {
    _createdAt: "2025-01-15",
    views: 48,
    author: { _id: 3, name: "Pam Soup" },
    _id: 7,
    title: "MedAssist",
    description: "Telehealth platform for remote medical consultations",
    image: "/img/platform.jpg",
    category: "health",
  },
  {
    _createdAt: "2024-11-30",
    views: 90,
    author: { _id: 2, name: "Lory Scabs" },
    _id: 8,
    title: "TravelTales",
    description: "Personalized travel planning and booking service",
    image: "/img/travel.jpg",
    category: "tech",
  },
  {
    _createdAt: "2025-01-23",
    views: 60,
    author: { _id: 4, name: "Arthur Mole" },
    _id: 9,
    title: "GreenHub",
    description: "Community platform for environmental initiatives",
    image: "/img/grocery.jpg",
    category: "eco",
  },
  {
    _createdAt: "2024-12-18",
    views: 110,
    author: { _id: 1, name: "Joan Caldwell" },
    _id: 10,
    title: "GameVerse",
    description: "Platform for discovering and playing indie games",
    image: "/img/code.jpg",
    category: "games",
  },
  {
    _createdAt: "2025-01-27",
    views: 92,
    author: { _id: 7, name: "Christopher Lee" },
    _id: 11,
    title: "GreenEnergy Solutions",
    description: "Sustainable energy solutions for homes and businesses",
    image: "/img/eco.jpg",
    category: "environment",
  },
  {
    _createdAt: "2025-01-24",
    views: 68,
    author: { _id: 5, name: "Olivia Maladini" },
    _id: 12,
    title: "FitMe",
    description: "Personalized fitness coaching app",
    image: "/img/weights.jpg",
    category: "health",
  },
  {
    _createdAt: "2025-01-21",
    views: 42,
    author: { _id: 4, name: "David Moped" },
    _id: 13,
    title: "Langaroo",
    description: "Language learning platform with gamified approach",
    image: "/img/work.jpg",
    category: "education",
  },
  {
    _createdAt: "2025-01-18",
    views: 130,
    author: { _id: 1, name: "Erdowan Pomp" },
    _id: 14,
    title: "Creatify",
    description: "Online marketplace for handmade crafts and art",
    image: "/img/crafts.jpg",
    category: "arts",
  },
  {
    _createdAt: "2025-01-16",
    views: 80,
    author: { _id: 3, name: "Genevieve Saq" },
    _id: 15,
    title: "FinWiz",
    description: "Financial management app for millennials",
    image: "/img/finance.jpg",
    category: "finance",
  },
];
